version: '3'

services:
  mongodb:
    image: mongo:latest

    environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=pass12345
      - MONGODB_DATABASE=test
    ports:
      - 27017:27017
    restart: unless-stopped
